spring.application.name=calculator-cicd
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
app.instance=${APP_INSTANCE:LOCAL}
app.version=${APP_VERSION:dev}